"""Initial schema

Revision ID: bd0fe111cf45
Revises: 
Create Date: 2026-07-17 10:41:26.786108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0fe111cf45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_types',
    sa.Column('code', sa.String(length=30), nullable=False, comment='Xizmat kodi: ambulance, fire, police, fvv, gas'),
    sa.Column('name_uz', sa.String(length=100), nullable=False, comment="O'zbekcha nomi"),
    sa.Column('name_ru', sa.String(length=100), nullable=False, comment='Ruscha nomi'),
    sa.Column('phone_number', sa.String(length=10), nullable=False, comment="Qo'ng'iroq raqami (103, 101, ...)"),
    sa.Column('color_hex', sa.String(length=10), nullable=False, comment='Xizmat rangi (HEX)'),
    sa.Column('icon', sa.String(length=50), nullable=False, comment='FontAwesome ikon klassi'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Xizmat faolmi?'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('service_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_types_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('oneid_pin', sa.String(length=255), nullable=False, comment='OneID PIN (AES-256 bilan shifrlangan)'),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('PATIENT', 'DISPATCHER', 'BRIGADE', 'ADMIN', name='user_role_enum', create_constraint=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oneid_pin'),
    sa.UniqueConstraint('phone')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('brigades',
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BUSY', 'EN_ROUTE', 'OFFLINE', name='brigade_status_enum', create_constraint=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('service_type_id', sa.UUID(), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True, comment='Brigada ixtisoslashuvi, masalan: kardiologiya, qutqaruv'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_number')
    )
    with op.batch_alter_table('brigades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brigades_id'), ['id'], unique=False)

    op.create_table('dispatchers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('service_type_id', sa.UUID(), nullable=False),
    sa.Column('is_on_duty', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('patients',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('blood_type', sa.String(length=10), nullable=True, comment='Qon guruhi (masalan: A+, B-, O+)'),
    sa.Column('allergies', sa.JSON(), nullable=True, comment="Allergiyalar ro'yxati"),
    sa.Column('chronic_conditions', sa.JSON(), nullable=True, comment="Surunkali kasalliklar ro'yxati"),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('brigade_members',
    sa.Column('brigade_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brigade_id'], ['brigades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('brigade_id', 'user_id')
    )
    op.create_table('emergency_calls',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('service_type_id', sa.UUID(), nullable=True),
    sa.Column('brigade_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'EN_ROUTE', 'ARRIVED', 'COMPLETED', 'CANCELLED', name='call_status_enum', create_constraint=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_multi_service', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('parent_call_id', sa.UUID(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level_enum', create_constraint=True), nullable=True),
    sa.Column('risk_confidence', sa.Float(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brigade_id'], ['brigades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_call_id'], ['emergency_calls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_calls_id'), ['id'], unique=False)

    op.create_table('call_audio_logs',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['emergency_calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_audio_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_audio_logs_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_audio_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_audio_logs_id'))

    op.drop_table('call_audio_logs')
    with op.batch_alter_table('emergency_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_calls_id'))

    op.drop_table('emergency_calls')
    op.drop_table('brigade_members')
    op.drop_table('patients')
    op.drop_table('dispatchers')
    with op.batch_alter_table('brigades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brigades_id'))

    op.drop_table('brigades')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('service_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_types_id'))

    op.drop_table('service_types')
    # ### end Alembic commands ###
